// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnlgianmqlcndjyovlxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ubGdpYW5tcWxjbmRqeW92bHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2Mjg3NjYsImV4cCI6MjA2NTIwNDc2Nn0.ho1BxNdFOMpeIe-cdzyQ_412xE493WMwjeWZDkf3hpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);