// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhqfvxxffhqqxuofzdhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxocWZ2eHhmZmhxcXh1b2Z6ZGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2Mjc4NDQsImV4cCI6MjA2NTIwMzg0NH0.sQlojhGQvUhZiyM-FElchtFU2tKHDE6p-PDW4IZmyGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);